#!/bin/bash
#
# Script for setting up the root (DBA) pgsql user
#
postgrespass=`/usr/bin/apg -MNCL -a 1 -m 16 -n 1`
postgreshome=/var/lib/pgsql
hostname=`/bin/hostname`

psql -c " ALTER USER postgres password '$postgrespass';"

printf "localhost:5432:postgres:*:" > $postgreshome/.pgpass

printf $postgrespass >> $postgreshome/.pgpass

chmod 600 $postgreshome/.pgpass

unset postgrespass


echo "Don't forget to archive the postgres user's password." | /bin/mailx -s "PostgreSQL set up on $hostname" jam265@cornell.edu

echo "#!/bin/sh

echo 'pgsql_initial_setup has already been run on this server.  Remove it and re-run puppet if needed.'
" > /cul/bin/pgsql_initial_setup
